### ISSUE TITLE
Precipitation visualization

### ISSUE THREAD

**Issue by desik23** [nex-dcp30-intro/notebook#15]

**Comment by joedecesaro** [comment]
<img width="756" alt="image" src="https://user-images.githubusercontent.com/88209601/142785252-dbc038e5-836e-4bd7-bfb1-c27db31146d9.png">

<img width="739" alt="image" src="https://user-images.githubusercontent.com/88209601/142785720-5513e713-063e-4e5c-8b24-3bd582ca7ce1.png">
