### ISSUE TITLE
Temperature visualization

### ISSUE THREAD

**Issue by desik23** [nex-dcp30-intro/notebook#16]

**Comment by joedecesaro** [comment]
<img width="715" alt="image" src="https://user-images.githubusercontent.com/88209601/142785776-3851700c-bf51-419b-b428-a3129b69084a.png">

<img width="725" alt="image" src="https://user-images.githubusercontent.com/88209601/142785789-dfecc4a0-edb2-43e3-a037-a2bc09f5d355.png">
