### ISSUE TITLE
Histogram

### ISSUE THREAD

**Issue by desik23** [nex-dcp30-intro/notebook#18]

**Comment by joedecesaro** [comment]
<img width="482" alt="image" src="https://user-images.githubusercontent.com/88209601/142785199-3465c53d-6455-4a83-ae51-18edc1fcdd5b.png">

<img width="505" alt="image" src="https://user-images.githubusercontent.com/88209601/142785220-bf524bd8-dc38-4cd2-86ae-4eb1f02db908.png">
